import { Inter } from "next/font/google";
import "@/assets/css/bootstrap-reboot.min.css"
import "@/assets/css/bootstrap-grid.min.css"
import "@/assets/css/owl.carousel.min.css"
import "@/assets/css/slider-radio.css"
import "@/assets/css/select2.min.css"
import "@/assets/css/magnific-popup.css"
import "@/assets/css/plyr.css"
import "@/assets/css/main.css"
import "@/assets/css/custom.css"

import Script from "next/script";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import AppHeader from "@/components/layouts/header";
import AppFooter from "@/components/layouts/footer";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "vudevweb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body suppressHydrationWarning={true}>
        <AntdRegistry>
          <AppHeader />
          {children}
          {/* <AppFooter /> */}
        </AntdRegistry>

        <Script src="/js/jquery-3.5.1.min.js" />
        <Script src="/js/bootstrap.bundle.min.js" />
        <Script src="/js/owl.carousel.min.js" />
        <Script src="/js/slider-radio.js" />
        <Script src="/js/select2.min.js" />
        <Script src="/js/smooth-scrollbar.js" />
        <Script src="/js/jquery.magnific-popup.min.js" />
        <Script src="/js/plyr.min.js" />
        <Script src="/js/main.js" />
      </body>
    </html>
  );
}
